# Generated by Django 5.2.6 on 2025-09-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_seed_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, help_text='Apellidos del usuario', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad de residencia', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento_identidad',
            field=models.CharField(blank=True, help_text='Cédula de identidad o pasaporte', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, help_text='Nombres del usuario', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(blank=True, help_text='País de residencia', max_length=50, null=True),
        ),
    ]
