# Generated by Django 5.2.6 on 2025-09-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_seed_roles'),
        ('authz', '0002_seed_users'),
    ]

    operations = [
    ]
