# Generated by Django 5.2.6 on 2025-09-09 03:35

from django.db import migrations

def migrate_nombre_to_nombres_apellidos(apps, schema_editor):
    """Migrar datos del campo nombre a nombres/apellidos"""
    # Como el campo nombre ya fue removido en la migración anterior,
    # no podemos acceder a él. Esta migración será útil si hay datos existentes.
    pass

def reverse_migration(apps, schema_editor):
    """Reversión de la migración"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0003_remove_usuario_nombre_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_nombre_to_nombres_apellidos, reverse_migration),
    ]
