# Generated by Django 5.2.6 on 2025-09-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0004_auto_20250908_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(help_text='Apellidos del usuario', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(help_text='Nombres del usuario', max_length=100),
        ),
    ]
