# Generated by Django 5.2.6 on 2025-09-06 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('TOUR', 'TOUR'), ('ALOJAMIENTO', 'ALOJAMIENTO'), ('TRANSPORTE', 'TRANSPORTE'), ('ACTIVIDAD', 'ACTIVIDAD')], max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_min', models.PositiveSmallIntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capacidad_max', models.PositiveSmallIntegerField()),
                ('punto_encuentro', models.CharField(max_length=255)),
                ('visible_publico', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='servicios', to='catalogo.categoria')),
            ],
            options={
                'indexes': [models.Index(fields=['categoria'], name='catalogo_se_categor_cc6a9f_idx'), models.Index(fields=['tipo'], name='catalogo_se_tipo_5226e8_idx')],
            },
        ),
    ]
