# Generated by Django 5.2.6 on 2025-09-06 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authz', '0001_initial'),
        ('catalogo', '0001_initial'),
        ('cupones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=191, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA'), ('CANCELADA', 'CANCELADA'), ('REPROGRAMADA', 'REPROGRAMADA')], default='PENDIENTE', max_length=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='BOB', max_length=3)),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='cupones.cupon')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='authz.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_servicio', models.DateTimeField(blank=True, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reservas.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogo.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CONFIRMADO', 'CONFIRMADO'), ('CANCELADO', 'CANCELADO')], default='CONFIRMADO', max_length=10)),
                ('es_titular', models.BooleanField(default=False)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitantes', to='reservas.reserva')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='reservas.visitante')),
            ],
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario'], name='reservas_re_usuario_cdc4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='reservas_re_estado_7c17e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reservaservicio',
            unique_together={('reserva', 'servicio')},
        ),
        migrations.AddConstraint(
            model_name='reservavisitante',
            constraint=models.UniqueConstraint(condition=models.Q(('es_titular', True)), fields=('reserva',), name='uq_un_titular_por_reserva'),
        ),
        migrations.AlterUniqueTogether(
            name='reservavisitante',
            unique_together={('reserva', 'visitante')},
        ),
    ]
